services:
  prod:
    container_name: nextjs-static-site
    image: nextjs-static-site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8096:80
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
